import React from "react";
import { Tabs, Collapse, Typography } from "antd";
import "../styles/docs.css";
import { HomeNavbar } from "../components/HomeNavbar";
import { useAppSelector } from "../hooks";
import { NavigationBar } from "../components/NavigationBar";

const { Paragraph } = Typography;
const { Panel } = Collapse;

/* ----------------------------------
 Types
-----------------------------------*/

export type ManualSection = {
  id: string;
  title: string;
  icon?: React.ReactNode;
  description?: string;
  content?: React.ReactNode;
};

export type ManualTab = {
  id: string;
  label: string;
  sections: ManualSection[];
};

export type YapatUserManualProps = {
  title?: string;
  subtitle?: string;
  activeTab?: string;
  onTabChange?: (tabId: string) => void;
};

/* ----------------------------------
 Documentation Structure (EDIT HERE)
-----------------------------------*/

const MANUAL_TABS: ManualTab[] = [
  {
    id: "getting-started",
    label: "Getting Started",
    sections: [
      {
        id: "intro",
        icon: "📘",
        title: "What is YAPAT?",
        description:
          "YAPAT is a lightweight, human-in-the-loop system for the expert annotation of Passive Acoustic Monitoring (PAM) data. It provides an efficient workflow for exploring, labeling, and managing large audio datasets used in biodiversity monitoring and eco-acoustic research.",
        content: (
          <p>
            YAPAT supports multiple annotation strategies — from simple random
            sampling to AI-powered active learning — all accessible from a
            single unified workspace. It is designed for both individual
            researchers and collaborative teams.
          </p>
        ),
      },
      {
        id: "quick-start",
        icon: "⚡",
        title: "Quick Start Guide",
        description: "Get up and running with YAPAT in just a few steps.",
        content: (
          <ol>
            <li>
              <strong>Upload a dataset</strong> — go to{" "}
              <strong>Dataset Management</strong> and register your audio
              recordings.
            </li>
            <li>
              <strong>Open the Annotation Hub</strong> — navigate to{" "}
              <strong>Annotate</strong> from the dashboard.
            </li>
            <li>
              <strong>Select a dataset and a feed mode</strong> — choose{" "}
              <em>Random</em> for broad coverage, <em>Similarity</em> to find
              acoustically similar snippets, or <em>Active Learning</em> for
              model-guided annotation.
            </li>
            <li>
              <strong>Generate a feed</strong> — click <em>Generate Feed</em>{" "}
              to load a batch of snippets. For similarity-based feeds, you will
              need to compute embeddings first.
            </li>
            <li>
              <strong>Start annotating</strong> — listen to each snippet,
              inspect the spectrogram, and assign species labels.
            </li>
          </ol>
        ),
      },
    ],
  },
  {
    id: "datasets",
    label: "Datasets",
    sections: [
      {
        id: "dataset-management",
        icon: "🗂️",
        title: "Dataset Management",
        description:
          "Upload, organise, and manage large PAM datasets.",
        content: (
          <>
            <p>
              The <strong>Datasets</strong> screen lists all datasets registered
              in your workspace. Each entry shows a summary of annotation
              progress so you can quickly assess how much of the data has been
              reviewed.
            </p>
            <br />
            <p>
              From this view you can:
            </p>
            <ul>
              <li>Browse and register new audio recordings.</li>
              <li>
                Monitor annotation coverage across datasets and individual
                feeds.
              </li>
              <li>
                Launch feed generation directly using the{" "}
                <strong>Generate Feed</strong> action on each dataset card.
              </li>
              <li>
                Manage <strong>Quick Labels</strong> — a per-dataset shortlist
                of species labels surfaced in the Annotation Hub for faster
                labeling.
              </li>
            </ul>
          </>
        ),
      },
      {
        id: "embeddings",
        icon: "🔢",
        title: "Embeddings",
        description:
          "Audio embeddings power similarity search and Active Learning inference.",
        content: (
          <>
            <p>
              Before using the <em>Similarity</em> feed or running Active
              Learning inference, embeddings must be computed for the dataset.
              Embeddings are dense vector representations of audio snippets
              generated by a pre-trained model (e.g. BirdNET).
            </p>
            <br />
            <p>
              Embedding computation is triggered from the feed generation
              dialog or from the dataset detail view. The job runs
              asynchronously in the background — you can monitor progress via
              the task status indicator.
            </p>
          </>
        ),
      },
    ],
  },
  {
    id: "annotation-hub",
    label: "Annotation Hub",
    sections: [
      {
        id: "hub-overview",
        icon: "🎛️",
        title: "Overview",
        description:
          "The Annotation Hub is the unified workspace for all annotation modes.",
        content: (
          <>
            <p>
              The <strong>Annotation Hub</strong> (<code>/annotate</code>) is
              the central workspace in YAPAT. It supports five annotation modes,
              all accessible from the same interface via the mode switcher in
              the toolbar:
            </p>
            <br />
            <ul>
              <li>
                <strong>Random</strong> — loads a random sample of snippets
                from the selected dataset. Good for broad initial coverage.
              </li>
              <li>
                <strong>Similarity</strong> — retrieves snippets acoustically
                similar to a reference audio clip you upload. Useful for
                finding more examples of a specific call type.
              </li>
              <li>
                <strong>Active Learning (AL)</strong> — uses a PAM model to
                rank snippets by uncertainty and surface the most informative
                ones for labeling. The model retrains automatically as you
                provide feedback.
              </li>
              <li>
                <strong>Validate</strong> — similar to AL mode but focused on
                reviewing and correcting existing model predictions rather than
                cold-start labeling.
              </li>
              <li>
                <strong>Filter</strong> — query snippets using metadata filters
                (recording, time range, annotation status, etc.).
              </li>
            </ul>
          </>
        ),
      },
      {
        id: "hub-random-similarity",
        icon: "🎲",
        title: "Random & Similarity Feeds",
        description: "Browse and annotate snippets using random or similarity-based sampling.",
        content: (
          <>
            <p>
              In <strong>Random</strong> and <strong>Similarity</strong> modes,
              the hub displays a scrollable feed of snippet cards. Each card
              shows:
            </p>
            <br />
            <ul>
              <li>A spectrogram of the audio snippet.</li>
              <li>An integrated audio player.</li>
              <li>
                A compact label picker with quick labels and a GBIF species
                search.
              </li>
              <li>
                Existing annotations from you or your teammates (shown with
                contributor names).
              </li>
            </ul>
            <br />
            <p>
              Labels are saved automatically as you select them. You can filter
              the feed by annotation status (<em>any</em>,{" "}
              <em>annotated only</em>, or <em>unannotated only</em>) from the
              feed configuration dialog.
            </p>
            <br />
            <p>
              Feeds are persisted per user and dataset so you can close the
              browser and resume where you left off.
            </p>
          </>
        ),
      },
      {
        id: "hub-al",
        icon: "🤖",
        title: "Active Learning Mode",
        description:
          "Use model-guided sampling to focus annotation effort on the most informative snippets.",
        content: (
          <>
            <p>
              Active Learning mode uses a PAM (Passive Acoustic Monitoring)
              classifier to rank unlabeled snippets by prediction uncertainty.
              The most uncertain snippets are surfaced first, making each
              annotation maximally useful for improving the model.
            </p>
            <br />
            <p>
              <strong>Workflow:</strong>
            </p>
            <ol>
              <li>
                Select a dataset and configure the inference settings (model
                checkpoint, sampling strategy, number of results).
              </li>
              <li>
                Click <strong>Generate Feed</strong> to run inference. The feed
                loads the top-K snippets ranked by the selected sampling
                strategy.
              </li>
              <li>
                For each snippet, listen to the audio and inspect the
                spectrogram. Then assign one or more species labels using the
                label picker. Labels are saved automatically as you select them.
              </li>
              <li>
                Once enough annotations are collected (configurable threshold),
                the model retrains automatically. The feed refreshes with
                updated rankings after retraining completes.
              </li>
            </ol>
            <br />
            <p>
              The <strong>projection view</strong> (UMAP/t-SNE) provides a 2D
              overview of all snippets in the feed, colored by sampling score or
              assigned label, to help you navigate and identify acoustic
              clusters.
            </p>
          </>
        ),
      },
    ],
  },
  {
    id: "label-management",
    label: "Label Management",
    sections: [
      {
        id: "label-space",
        icon: "🏷️",
        title: "Label Space",
        description:
          "Build and manage the set of species labels available for annotation.",
        content: (
          <>
            <p>
              The <strong>Label Management</strong> screen (
              <code>/pre-annotation</code>) is where you define the label space
              for your annotation sessions. The label space is the list of
              species or sound categories that annotators can assign to
              snippets.
            </p>
            <br />
            <p>
              You can build the label space using the built-in{" "}
              <strong>taxonomy chatbot</strong>, which suggests species based on
              natural language descriptions of the target soundscape. Labels can
              also be added manually or imported.
            </p>
            <br />
            <p>
              Once the label space is finalised, it can be{" "}
              <strong>frozen and published</strong> to make it available to all
              team members for a given annotation campaign.
            </p>
          </>
        ),
      },
      {
        id: "quick-labels",
        icon: "⚡",
        title: "Quick Labels",
        description:
          "Per-dataset shortlists for faster labeling in the Annotation Hub.",
        content: (
          <p>
            Each dataset can have a set of <strong>Quick Labels</strong> — a
            curated shortlist of the most relevant species for that dataset.
            Quick labels are surfaced prominently in the Annotation Hub label
            picker, reducing the need to search through the full species list
            for common calls. Quick labels are managed from the dataset card on
            the Datasets screen.
          </p>
        ),
      },
    ],
  },
  {
    id: "teams",
    label: "Teams",
    sections: [
      {
        id: "team-management",
        icon: "👥",
        title: "Team Management",
        description:
          "Invite collaborators and coordinate annotation across your team.",
        content: (
          <>
            <p>
              The <strong>Teams</strong> screen allows workspace administrators
              and team owners to:
            </p>
            <ul>
              <li>Create teams and invite collaborators by email.</li>
              <li>
                Assign roles (<em>admin</em>, <em>team owner</em>,{" "}
                <em>annotator</em>) to control access levels.
              </li>
              <li>Associate datasets with teams for collaborative annotation.</li>
              <li>Track per-member annotation contributions.</li>
            </ul>
            <br />
            <p>
              Invitation links can be copied and shared directly. Team members
              can annotate the same feeds simultaneously; their contributions
              are tracked separately and displayed on each snippet card.
            </p>
          </>
        ),
      },
    ],
  },
  {
    id: "history",
    label: "Feed History",
    sections: [
      {
        id: "feed-history",
        icon: "🕓",
        title: "Feed History",
        description: "Review and re-open previously generated annotation feeds.",
        content: (
          <>
            <p>
              The <strong>Feed History</strong> screen (<code>/history</code>)
              provides a log of all feeds generated across your datasets. For
              each feed you can see:
            </p>
            <ul>
              <li>The dataset and feed mode used.</li>
              <li>The number of snippets and annotation progress.</li>
              <li>When the feed was generated and by whom.</li>
            </ul>
            <br />
            <p>
              You can re-open any previous feed to continue annotating or to
              review already-annotated snippets. This is useful for auditing
              annotation quality or resuming an incomplete session.
            </p>
          </>
        ),
      },
    ],
  },
];

/* ----------------------------------
 Component
-----------------------------------*/

export const YapatUserManual: React.FC<YapatUserManualProps> = ({
  title = "User Manual",
  subtitle = "A complete guide to using YAPAT for PAM dataset management, AI-assisted annotation, and eco-acoustic analysis.",
}) => {
  const { isAuthenticated } = useAppSelector((state) => state.auth);
  return (
    <div>
      {isAuthenticated ? <NavigationBar /> : <HomeNavbar />}

      <section className="yapat-manual">
        {/* Header */}

        <header className="yapat-manual__header">
          <h1 className="text-2xl font-bold font-ibm-mono py-2">📖 {title}</h1>
          <p className="sub_description_text">{subtitle}</p>
        </header>

        {/* Tabs */}
        <Tabs
          defaultActiveKey="getting-started"
          items={MANUAL_TABS.map((tab) => ({
            key: tab.id,
            label: tab.label,
            children: (
              <Collapse accordion>
                {tab.sections.map((section) => (
                  <Panel
                    key={section.id}
                    header={
                      <span>
                        <span
                          style={{ marginRight: 8, fontFamily: "ibm-mono" }}
                        >
                          {section.icon}
                        </span>
                        {section.title}
                      </span>
                    }
                  >
                    {section.description && (
                      <Paragraph className="font-ibm-sans">
                        {section.description}
                      </Paragraph>
                    )}
                    {section.content}
                  </Panel>
                ))}
              </Collapse>
            ),
          }))}
        />
      </section>
    </div>
  );
};
